---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/notes":
    get:
      summary: list notes
      tags:
      - Notes
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
        '201':
          description: successfully authenticated
        '401':
          description: authentication failed
    post:
      summary: create note
      tags:
      - Notes
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: successfully authenticated
        '422':
          description: invalid request
        '401':
          description: authentication failed
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
              required:
              - title
              - body
  "/notes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show note
      tags:
      - Notes
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
        '201':
          description: successfully authenticated
        '401':
          description: authentication failed
    put:
      summary: update note
      tags:
      - Notes
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: successfully authenticated
        '422':
          description: invalid request
        '401':
          description: authentication failed
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
              required:
              - title
              - body
    delete:
      summary: delete note
      tags:
      - Notes
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
        '201':
          description: successfully authenticated
        '401':
          description: authentication failed
  "/users":
    post:
      summary: create user
      tags:
      - User Registration
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                age:
                  type: string
                password:
                  type: string
              required:
              - username
              - age
              - password
  "/login":
    post:
      summary: login user
      tags:
      - Login
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/auto_login":
    get:
      summary: auto_login user
      tags:
      - Auto Login
      security:
      - bearer_auth: []
      responses:
        '201':
          description: authentication successful
        '401':
          description: authentication failed
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: julienotesbackend.herokuapp.com
